### ISSUE TITLE
Unexpected latency due to rate limitation

### ISSUE THREAD

**Issue by stephenyin** [thombashi/tcconfig#111]
I got unexpected high latency when use "rate" to limit bandwidth.
```
tcset enp2s0 --rate 300K --loss 0 --delay 0ms --direction incoming --src-network 192.168.3.101
```
When host 192.168.3.101 tx-rate exceeds 300K the RTT is keeping grow up.
How can i make tcconfig to drop packets when tx-rate higher than rate limitation ? 

Thanks a lot.

**Comment by thombashi** [comment]
@stephenyin 
Are you trying to achieve for both bandwidth limitation with 300Kbps and low latency? if yes, that might be difficult.
Because `tc` implement bandwidth limitation by dropping packets.
However, there might be workarounds in some cases.
For example, if you specify `--src-port` option to your command, traffic of other ports will keep low latencies.
Could you possibly describe what you are trying to do and details of network traffic?

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
