### ISSUE TITLE
Possibility to modify the burst and cburst through command line

### ISSUE THREAD

**Issue by alvarolaserna** [thombashi/tcconfig#152]
Right now the current implementation assign the bitrate use for the limitation as the size of the burst allowed, i.e. if I choose a 200Kbit/s rate I'll get a burst and cburst of 200Kbit.

# Solution I'd like
It would be nice to have a flag, or 2 to assign this values, and if not default to 0 (no burst):
--burst/--cburst

# Additional context
You can see this assignment in the https://github.com/thombashi/tcconfig/blob/master/tcconfig/shaper/htb.py lines 115-121

**Comment by thombashi** [comment]
@alvarolaserna 
Thank you for your feedback.

Could you describe in more detail what the problem is?
I'm not sure why you need to change burst/cburst value.
According to `tc-htb`, calculated values (e.g. 25KB for 200kbps rate limit) would be sufficient.

> default to 0 (no burst):

no burst would not be possible. if you set to 0KB to burst/cburst, `tc` will automatically set burst/cburst values and these values are very low.
