### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by jacenrkohler** [thombashi/tcconfig#63]
It's telling me that it expects 4 octets. Does this mean that tcconfig does not support IPv6? or is there a flag I need to set.

**Comment by thombashi** [comment]
`tcconfig` does support IPv6. 

>is there a flag I need to set.

Yes. Please add `--ipv6` option when you use IPv6 addresses.

An execution example could be found here http://tcconfig.readthedocs.io/en/latest/pages/usage/tcset/index.html#using-ipv6

**Comment by jacenrkohler** [comment]
What order should that be in? currently I'm using the following:
tcset --device --eth0 --direction incoming --delay 500 --network fe80::a00:27ff:fe59:f5a3
I've tried several ways and it keeps telling me "error: unrecognized arguments: --ipv6"
Where in that should the --ipv6 flag go?

**Comment by thombashi** [comment]
@jacenrkohler 
Thank you for your additional information.

The option not consider order.
I guess that the error caused from installed `tcconfig` version in your environment.
`tcconfig` supported IPv6 since `version 0.9.0`.
Could you check the installed `tcconfig` version with `tcset --version`?
If the version is lower than `0.9.0`, please upgrade to `tcconfig 0.9.0` with `pip install tcconfig --upgrade` command.

In my environment (`Debian 8.6`, `tcconfig 0.9.0`, `Python 2.7.9`), your command succeeded.

```
# tcset --device eth0 --direction incoming --delay 500 --network fe80::a00:27ff:fe59:f5a3 --ipv6
# tcshow --device eth0 --ipv6
{
    "eth0": {
        "outgoing": {},
        "incoming": {
            "network=fe80::a00:27ff:fe59:f5a3/128, protocol=ipv6": {
                "delay": "500.0",
                "rate": "32G"
            }
        }
    }
}
```

**Comment by jacenrkohler** [comment]
There's the problem. I was on version 0.7.0. Thanks for the help!

**Comment by thombashi** [comment]
It's my pleasure.
I'll close the issue then.
